name = "ZAU"
grammar = "zau"
path_suffixes = ["zau"]
line_comments = ["// "]
block_comment = ["<!--", "-->"]

[brackets]
characters = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = true },
  { start = "<", end = ">", close = true, newline = true },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false }
]

[language_servers]
zau-lsp = {}
