# zau/compiler/bridge.py
"""
ZAU Type Generation Bridge
Inspects registered server actions and ORM models, then generates TypeScript definitions.
"""

import inspect
from typing import Dict, Any, List, get_type_hints

def python_type_to_ts(py_type: Any) -> str:
    if py_type is None or py_type is type(None):
        return "void"
    if py_type in (int, float):
        return "number"
    if py_type is str:
        return "string"
    if py_type is bool:
        return "boolean"
    if py_type in (dict, Dict):
        return "Record<string, any>"
    if py_type in (list, List):
        return "any[]"
    
    # Check origin
    origin = getattr(py_type, "__origin__", None)
    if origin in (list, List):
        args = getattr(py_type, "__args__", ())
        sub = python_type_to_ts(args[0]) if args else "any"
        return f"{sub}[]"
    if origin in (dict, Dict):
        return "Record<string, any>"

    name = getattr(py_type, "__name__", str(py_type))
    return name

def generate_typescript_definitions(app: Any) -> str:
    """Generate zau-api.d.ts from ZAU app server actions."""
    lines = [
        "// Auto-generated by ZAU Type Bridge",
        "// Do not edit manually.",
        "",
        "export interface ZAUClientAPI {"
    ]

    actions = getattr(app, "_server_actions", {})
    for path, func in actions.items():
        sig = inspect.signature(func)
        hints = get_type_hints(func)
        
        args_ts = []
        for param_name, param in sig.parameters.items():
            if param_name in ("request", "session", "db"):
                continue
            p_type = hints.get(param_name, Any)
            ts_t = python_type_to_ts(p_type)
            is_optional = param.default is not inspect.Parameter.empty
            args_ts.append(f"{param_name}{'?' if is_optional else ''}: {ts_t}")

        ret_type = hints.get("return", Any)
        ret_ts = python_type_to_ts(ret_type)
        if ret_ts != "void":
            ret_ts = f"Promise<{ret_ts}>"
        else:
            ret_ts = "Promise<any>"

        method_name = func.__name__
        lines.append(f"  /** Call server action: {path} */")
        lines.append(f"  {method_name}({', '.join(args_ts)}): {ret_ts};")

    lines.append("}")
    lines.append("")
    lines.append("declare global {")
    lines.append("  interface Window {")
    lines.append("    zauAPI: ZAUClientAPI;")
    lines.append("  }")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)
